apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
data:
  OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"
  OAUTH2_PROXY_COOKIE_REFRESH: "5m"
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
  OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
  OAUTH2_PROXY_OIDC_GROUPS_CLAIM: "groups"
  OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
  OAUTH2_PROXY_PROXY_PREFIX: "/oauth2"
  OAUTH2_PROXY_REVERSE_PROXY: "true"
  OAUTH2_PROXY_SCOPE: "openid email profile"
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_WHITELIST_DOMAINS: "*.zeit.de"
